### ISSUE TITLE
js-parser-tests does not build - missing file external/rt.lisp

### ISSUE THREAD

**Issue by quicklisp** [gonzojive/js-parser#2]
When I try to build js-parser-tests, the system refers to a file that's not present: external/rt.lisp.

**Comment by quicklisp** [comment]
Because of this failure, I won't be able to include js-parser in Quicklisp in the next release.

**Comment by gonzojive** [comment]
Thanks for filing a bug report.  All tests pass for me after adding the missing file, which I plucked from here:
https://github.com/alanruttenberg/js-to-paren/blob/c947fcbd394e5ad65d2f88e995a46363b218626f/external/rt.lisp
